<a href="https://colab.research.google.com/github/arthur-siqueira/metodos-numericos/blob/main/matrix_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercise 5-1**

In [1]:
import numpy as np

matriz = np.arange(12).reshape(3, 4)

print("Matriz criada:")
print(matriz)
print("-" * 20)

linha_idx = 1
coluna_idx = 3

# Extrai o elemento usando os índices definidos
elemento = matriz[linha_idx, coluna_idx]

print(f"The matrix element at index ({linha_idx},{coluna_idx}) is {elemento}.")

Matriz criada:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
The matrix element at index (1,3) is 7.


**Exercise 5-2**

In [2]:
# Cria a matriz C original (10x10 com números de 0 a 99)
matrix_C = np.arange(100).reshape(10, 10)

print("Matriz Original C (10x10):")
print(matrix_C)
print("\n" + "-"*30 + "\n")

# 2. Usa fatiamento (slicing) para extrair a submatriz C1
# O slice [:5, :5] pega as linhas do índice 0 até 4 e as colunas do índice 0 até 4.
submatrix_C1 = matrix_C[:5, :5]

print("Submatriz Extraída C1 (5x5):")
print(submatrix_C1)

Matriz Original C (10x10):
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

------------------------------

Submatriz Extraída C1 (5x5):
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


**Exercise 5-3**

In [3]:
# Cria a matriz original C (10x10 com números de 0 a 99)
matriz_C = np.arange(100).reshape(10, 10)

print("Matriz Original C:")
print(matriz_C)
print("\n" + "-"*40 + "\n")

# Extrai os quatro blocos 5x5 usando fatiamento (slicing)
bloco_superior_esquerdo = matriz_C[:5, :5]
bloco_superior_direito = matriz_C[:5, 5:]
bloco_inferior_esquerdo = matriz_C[5:, :5]
bloco_inferior_direito = matriz_C[5:, 5:]

matriz_reorganizada = np.block([
    [bloco_inferior_direito, bloco_inferior_esquerdo],
    [bloco_superior_direito, bloco_superior_esquerdo]
])

Matriz Original C:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

----------------------------------------



**Exercise 5-4**

In [4]:
def adicao_de_matrizes_loop(A, B):
    """
    Soma duas matrizes, A e B, elemento a elemento usando laços for.

    Args:
        A: A primeira matriz (array NumPy).
        B: A segunda matriz (array NumPy).

    Returns:
        Uma nova matriz que é a soma de A e B.

    Raises:
        ValueError: Se as matrizes A e B não tiverem as mesmas dimensões.
    """
    # 1. Verifica se as dimensões são compatíveis antes de começar
    if A.shape != B.shape:
        raise ValueError("Erro: As matrizes devem ter as mesmas dimensões para serem somadas.")

    # 2. Cria uma matriz de resultado com o mesmo formato de A, preenchida com zeros
    C = np.zeros_like(A)

    # 3. Itera sobre as linhas (usando o número de linhas da matriz A)
    for i in range(A.shape[0]):
        # 4. Itera sobre as colunas (usando o número de colunas da matriz A)
        for j in range(A.shape[1]):
            # 5. Soma os elementos na posição (i, j) e armazena no resultado
            C[i, j] = A[i, j] + B[i, j]

    return C

# --- Demonstração com matrizes de tamanhos iguais ---
print("--- TESTE 1: Matrizes de tamanhos compatíveis ---")

# Cria duas matrizes 2x3 aleatórias
matriz_A = np.random.randint(10, size=(2, 3))
matriz_B = np.random.randint(10, size=(2, 3))

print("Matriz A:\n", matriz_A)
print("\nMatriz B:\n", matriz_B)

# Soma usando nossa função com loops
resultado_loop = adicao_de_matrizes_loop(matriz_A, matriz_B)
print("\nResultado com a função de loops:\n", resultado_loop)

# Soma usando a forma otimizada do NumPy para verificar
resultado_numpy = matriz_A + matriz_B
print("\nResultado com o operador '+' do NumPy (para verificação):\n", resultado_numpy)

print("\nOs resultados são idênticos?", np.array_equal(resultado_loop, resultado_numpy))

print("\n" + "="*50 + "\n")
print("--- TESTE 2: Matrizes de tamanhos incompatíveis ---")

# Cria duas matrizes com dimensões diferentes
matriz_M = np.random.randint(10, size=(2, 3)) # 2 linhas, 3 colunas
matriz_N = np.random.randint(10, size=(3, 2)) # 3 linhas, 2 colunas

print("Matriz M (2x3):\n", matriz_M)
print("\nMatriz N (3x2):\n", matriz_N)

# Tenta somar as matrizes incompatíveis
try:
    resultado_erro = adicao_de_matrizes_loop(matriz_M, matriz_N)
except ValueError as e:
    print(f"\nUma exceção foi capturada, como esperado:")
    print(e)

--- TESTE 1: Matrizes de tamanhos compatíveis ---
Matriz A:
 [[5 6 1]
 [9 0 2]]

Matriz B:
 [[2 8 5]
 [5 8 8]]

Resultado com a função de loops:
 [[ 7 14  6]
 [14  8 10]]

Resultado com o operador '+' do NumPy (para verificação):
 [[ 7 14  6]
 [14  8 10]]

Os resultados são idênticos? True


--- TESTE 2: Matrizes de tamanhos incompatíveis ---
Matriz M (2x3):
 [[1 0 2]
 [7 2 2]]

Matriz N (3x2):
 [[4 5]
 [1 4]
 [7 8]]

Uma exceção foi capturada, como esperado:
Erro: As matrizes devem ter as mesmas dimensões para serem somadas.


**Exercise 5-5**

In [5]:
A = np.random.randint(10, size=(3, 4))
B = np.random.randint(10, size=(3, 4))

# Define um escalar
sigma = 3

print("Dados iniciais")
print(f"Escalar σ = {sigma}\n")
print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\n" + "="*30 + "\n")

print("Calculando o lado esquerdo: σ * (A + B)")
soma_matrizes = A + B
lado_esquerdo = sigma * soma_matrizes

print("Resultado do lado esquerdo:")
print(lado_esquerdo)
print("\n" + "="*30 + "\n")

print("Calculando o lado direito: (σ * A) + (σ * B)")
sigma_A = sigma * A
sigma_B = sigma * B
lado_direito = sigma_A + sigma_B

print("Resultado do lado direito:")
print(lado_direito)
print("\n" + "="*30 + "\n")

sao_iguais = np.array_equal(lado_esquerdo, lado_direito)

print("Verificação Final")
print(f"O resultado de σ(A + B) é igual ao resultado de σA + σB? \nResposta: {sao_iguais}")

Dados iniciais
Escalar σ = 3

Matriz A:
[[1 8 3 1]
 [8 9 0 7]
 [3 7 9 3]]

Matriz B:
[[9 1 1 5]
 [5 7 1 5]
 [9 7 1 1]]


Calculando o lado esquerdo: σ * (A + B)
Resultado do lado esquerdo:
[[30 27 12 18]
 [39 48  3 36]
 [36 42 30 12]]


Calculando o lado direito: (σ * A) + (σ * B)
Resultado do lado direito:
[[30 27 12 18]
 [39 48  3 36]
 [36 42 30 12]]


Verificação Final
O resultado de σ(A + B) é igual ao resultado de σA + σB? 
Resposta: True


**Exercise 5-6**

In [6]:
import numpy as np

def multiplicacao_de_matrizes_loop(A, B):
    """
    Multiplica duas matrizes, A e B, usando três laços for aninhados.

    Args:
        A: A primeira matriz (array NumPy).
        B: A segunda matriz (array NumPy).

    Returns:
        Uma nova matriz que é o produto de A e B.

    Raises:
        ValueError: Se as matrizes não forem compatíveis para multiplicação.
    """
    # Verifica se a multiplicação é possível
    # O número de colunas de A deve ser igual ao número de linhas de B.
    if A.shape[1] != B.shape[0]:
        raise ValueError("Dimensões incompatíveis! O número de colunas de A deve ser igual ao de linhas de B.")

    # Prepara a matriz de resultado C com as dimensões corretas e preenchida com zeros
    # Dimensões de C: (linhas de A, colunas de B)
    C = np.zeros((A.shape[0], B.shape[1]))

    # Itera sobre cada célula da matriz resultante C
    # Laço para as linhas de C (e A)
    for i in range(A.shape[0]):
        # Laço para as colunas de C (e B)
        for j in range(B.shape[1]):
            # Laço para o produto escalar (colunas de A / linhas de B)
            soma = 0
            for k in range(A.shape[1]):
                soma += A[i, k] * B[k, j]

            # Atribui o resultado da soma à célula C[i, j]
            C[i, j] = soma

    return C

# Demonstração e Confirmação
print("--- Demonstração da Multiplicação de Matrizes ---")

# Cria duas matrizes compatíveis: A (3x4) e B (4x2)
matriz_A = np.random.randint(1, 10, size=(3, 4))
matriz_B = np.random.randint(1, 10, size=(4, 2))

print("Matriz A (3x4):")
print(matriz_A)
print("\nMatriz B (4x2):")
print(matriz_B)

# Confirmação dos resultados
print("\n" + "="*50 + "\n")

# Resultado usando nossa função com loops
resultado_loop = multiplicacao_de_matrizes_loop(matriz_A, matriz_B)
print("Resultado com a função de loops (3x2):")
print(resultado_loop)

# Resultado usando o operador '@' do NumPy
resultado_numpy = matriz_A @ matriz_B
print("\nResultado com o operador '@' do NumPy (3x2):")
print(resultado_numpy)

# Verifica se os dois resultados são numericamente iguais
sao_iguais = np.allclose(resultado_loop, resultado_numpy)
print(f"\nOs resultados são idênticos? {sao_iguais}")

--- Demonstração da Multiplicação de Matrizes ---
Matriz A (3x4):
[[3 6 6 9]
 [2 8 9 3]
 [4 6 1 9]]

Matriz B (4x2):
[[4 5]
 [4 1]
 [8 7]
 [1 9]]


Resultado com a função de loops (3x2):
[[ 93. 144.]
 [115. 108.]
 [ 57. 114.]]

Resultado com o operador '@' do NumPy (3x2):
[[ 93 144]
 [115 108]
 [ 57 114]]

Os resultados são idênticos? True


**Exercise 5-7**

In [7]:
print("Matrizes não quadradas")

# Cria quatro matrizes com números aleatórios e tamanhos específicos
L = np.random.randn(2, 6)  # 2x6
I = np.random.randn(6, 3)  # 6x3
V = np.random.randn(3, 5)  # 3x5
E = np.random.randn(5, 2)  # 5x2

print("Dimensões: L(2x6), I(6x3), V(3x5), E(5x2)")

# Multiplica as quatro matrizes e transpõe o produto
print("\nPasso 2: Calculando (L @ I @ V @ E).T")
produto = L @ I @ V @ E
resultado_passo2 = produto.T
print("Resultado do Passo 2 (dimensões {}):\n".format(resultado_passo2.shape), resultado_passo2)

# Transpõe cada matriz individualmente e multiplica na mesma ordem
print("\nPasso 3: Calculando L.T @ I.T @ V.T @ E.T (ordem original)")
try:
    resultado_passo3 = L.T @ I.T @ V.T @ E.T
except ValueError as e:
    print("ERRO! Como esperado, a multiplicação falhou.")
    print("Motivo:", e)
    print("Isso ocorre porque as dimensões se tornam incompatíveis (L.T é 6x2, I.T é 3x6).")

# Transpõe cada matriz e multiplica na ordem INVERSA (regra LIVE EVIL)
print("\nPasso 4: Calculando E.T @ V.T @ I.T @ L.T (ordem inversa)")
resultado_passo4 = E.T @ V.T @ I.T @ L.T
print("Resultado do Passo 4 (dimensões {}):\n".format(resultado_passo4.shape), resultado_passo4)

# Verificação final
print("O resultado do Passo 2 corresponde ao do Passo 4?", np.allclose(resultado_passo2, resultado_passo4))

Matrizes não quadradas
Dimensões: L(2x6), I(6x3), V(3x5), E(5x2)

Passo 2: Calculando (L @ I @ V @ E).T
Resultado do Passo 2 (dimensões (2, 2)):
 [[ 6.01323986  3.65137007]
 [14.75993948  2.69239089]]

Passo 3: Calculando L.T @ I.T @ V.T @ E.T (ordem original)
ERRO! Como esperado, a multiplicação falhou.
Motivo: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)
Isso ocorre porque as dimensões se tornam incompatíveis (L.T é 6x2, I.T é 3x6).

Passo 4: Calculando E.T @ V.T @ I.T @ L.T (ordem inversa)
Resultado do Passo 4 (dimensões (2, 2)):
 [[ 6.01323986  3.65137007]
 [14.75993948  2.69239089]]
O resultado do Passo 2 corresponde ao do Passo 4? True


In [8]:
print("Matrizes Quadradas ---")

# Cria quatro matrizes quadradas (4x4)
L_sq = np.random.randn(4, 4)
I_sq = np.random.randn(4, 4)
V_sq = np.random.randn(4, 4)
E_sq = np.random.randn(4, 4)
print("Dimensões: L, I, V, E todas 4x4")

# Multiplica e depois transpõe
produto_sq = L_sq @ I_sq @ V_sq @ E_sq
resultado_sq_passo2 = produto_sq.T
print("\nPasso 2: Resultado de (LIVE).T:\n", resultado_sq_passo2)

# Transpõe e multiplica na mesma ordem
resultado_sq_passo3 = L_sq.T @ I_sq.T @ V_sq.T @ E_sq.T
print("\nPasso 3: Resultado de L.T @ I.T @ V.T @ E.T (ordem original):\n", resultado_sq_passo3)


# Transpõe e multiplica na ordem inversa
resultado_sq_passo4 = E_sq.T @ V_sq.T @ I_sq.T @ L_sq.T
print("\nPasso 4: Resultado de E.T @ V.T @ I.T @ L.T (ordem inversa):\n", resultado_sq_passo4)


# Verificação final
print("O resultado do Passo 2 corresponde ao do Passo 3?", np.allclose(resultado_sq_passo2, resultado_sq_passo3))
print("O resultado do Passo 2 corresponde ao do Passo 4?", np.allclose(resultado_sq_passo2, resultado_sq_passo4))

Matrizes Quadradas ---
Dimensões: L, I, V, E todas 4x4

Passo 2: Resultado de (LIVE).T:
 [[-13.8338254   -1.10105413  -0.86381599  -4.62493766]
 [ -0.5598402    2.05390933  -2.66282457   0.7888548 ]
 [ -9.07959146   1.35593433   8.88752718  -5.75605513]
 [-17.40369104   3.27034524   2.34251831  -6.4889075 ]]

Passo 3: Resultado de L.T @ I.T @ V.T @ E.T (ordem original):
 [[  0.3701855   11.27792958 -11.37868955  -5.06189853]
 [  1.63460336  -1.16107904   3.29034023  -0.21827894]
 [  0.98311505  12.36516574   2.35261054 -11.33627934]
 [  2.59500821 -11.32719853  18.74343812   2.37140303]]

Passo 4: Resultado de E.T @ V.T @ I.T @ L.T (ordem inversa):
 [[-13.8338254   -1.10105413  -0.86381599  -4.62493766]
 [ -0.5598402    2.05390933  -2.66282457   0.7888548 ]
 [ -9.07959146   1.35593433   8.88752718  -5.75605513]
 [-17.40369104   3.27034524   2.34251831  -6.4889075 ]]
O resultado do Passo 2 corresponde ao do Passo 3? False
O resultado do Passo 2 corresponde ao do Passo 4? True
