<a href="https://colab.research.google.com/github/arthur-siqueira/metodos-numericos/blob/main/matrix_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercise 5-1**

In [1]:
import numpy as np

matriz = np.arange(12).reshape(3, 4)

print("Matriz criada:")
print(matriz)
print("-" * 20)

linha_idx = 1
coluna_idx = 3

# Extrai o elemento usando os índices definidos
elemento = matriz[linha_idx, coluna_idx]

print(f"The matrix element at index ({linha_idx},{coluna_idx}) is {elemento}.")

Matriz criada:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
The matrix element at index (1,3) is 7.


**Exercise 5-2**

In [2]:
# Cria a matriz C original (10x10 com números de 0 a 99)
matrix_C = np.arange(100).reshape(10, 10)

print("Matriz Original C (10x10):")
print(matrix_C)
print("\n" + "-"*30 + "\n")

# 2. Usa fatiamento (slicing) para extrair a submatriz C1
# O slice [:5, :5] pega as linhas do índice 0 até 4 e as colunas do índice 0 até 4.
submatrix_C1 = matrix_C[:5, :5]

print("Submatriz Extraída C1 (5x5):")
print(submatrix_C1)

Matriz Original C (10x10):
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

------------------------------

Submatriz Extraída C1 (5x5):
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


**Exercise 5-3**

In [3]:
# Cria a matriz original C (10x10 com números de 0 a 99)
matriz_C = np.arange(100).reshape(10, 10)

print("Matriz Original C:")
print(matriz_C)
print("\n" + "-"*40 + "\n")

# Extrai os quatro blocos 5x5 usando fatiamento (slicing)
bloco_superior_esquerdo = matriz_C[:5, :5]
bloco_superior_direito = matriz_C[:5, 5:]
bloco_inferior_esquerdo = matriz_C[5:, :5]
bloco_inferior_direito = matriz_C[5:, 5:]

matriz_reorganizada = np.block([
    [bloco_inferior_direito, bloco_inferior_esquerdo],
    [bloco_superior_direito, bloco_superior_esquerdo]
])

Matriz Original C:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

----------------------------------------



**Exercise 5-4**

In [4]:
def adicao_de_matrizes_loop(A, B):
    """
    Soma duas matrizes, A e B, elemento a elemento usando laços for.

    Args:
        A: A primeira matriz (array NumPy).
        B: A segunda matriz (array NumPy).

    Returns:
        Uma nova matriz que é a soma de A e B.

    Raises:
        ValueError: Se as matrizes A e B não tiverem as mesmas dimensões.
    """
    # 1. Verifica se as dimensões são compatíveis antes de começar
    if A.shape != B.shape:
        raise ValueError("Erro: As matrizes devem ter as mesmas dimensões para serem somadas.")

    # 2. Cria uma matriz de resultado com o mesmo formato de A, preenchida com zeros
    C = np.zeros_like(A)

    # 3. Itera sobre as linhas (usando o número de linhas da matriz A)
    for i in range(A.shape[0]):
        # 4. Itera sobre as colunas (usando o número de colunas da matriz A)
        for j in range(A.shape[1]):
            # 5. Soma os elementos na posição (i, j) e armazena no resultado
            C[i, j] = A[i, j] + B[i, j]

    return C

# --- Demonstração com matrizes de tamanhos iguais ---
print("--- TESTE 1: Matrizes de tamanhos compatíveis ---")

# Cria duas matrizes 2x3 aleatórias
matriz_A = np.random.randint(10, size=(2, 3))
matriz_B = np.random.randint(10, size=(2, 3))

print("Matriz A:\n", matriz_A)
print("\nMatriz B:\n", matriz_B)

# Soma usando nossa função com loops
resultado_loop = adicao_de_matrizes_loop(matriz_A, matriz_B)
print("\nResultado com a função de loops:\n", resultado_loop)

# Soma usando a forma otimizada do NumPy para verificar
resultado_numpy = matriz_A + matriz_B
print("\nResultado com o operador '+' do NumPy (para verificação):\n", resultado_numpy)

print("\nOs resultados são idênticos?", np.array_equal(resultado_loop, resultado_numpy))

print("\n" + "="*50 + "\n")
print("--- TESTE 2: Matrizes de tamanhos incompatíveis ---")

# Cria duas matrizes com dimensões diferentes
matriz_M = np.random.randint(10, size=(2, 3)) # 2 linhas, 3 colunas
matriz_N = np.random.randint(10, size=(3, 2)) # 3 linhas, 2 colunas

print("Matriz M (2x3):\n", matriz_M)
print("\nMatriz N (3x2):\n", matriz_N)

# Tenta somar as matrizes incompatíveis
try:
    resultado_erro = adicao_de_matrizes_loop(matriz_M, matriz_N)
except ValueError as e:
    print(f"\nUma exceção foi capturada, como esperado:")
    print(e)

--- TESTE 1: Matrizes de tamanhos compatíveis ---
Matriz A:
 [[8 1 0]
 [1 6 9]]

Matriz B:
 [[3 8 9]
 [9 5 2]]

Resultado com a função de loops:
 [[11  9  9]
 [10 11 11]]

Resultado com o operador '+' do NumPy (para verificação):
 [[11  9  9]
 [10 11 11]]

Os resultados são idênticos? True


--- TESTE 2: Matrizes de tamanhos incompatíveis ---
Matriz M (2x3):
 [[4 6 7]
 [9 6 3]]

Matriz N (3x2):
 [[4 6]
 [8 4]
 [7 3]]

Uma exceção foi capturada, como esperado:
Erro: As matrizes devem ter as mesmas dimensões para serem somadas.
