<a href="https://colab.research.google.com/github/arthur-siqueira/metodos-numericos/blob/main/matrix_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercise 5-1**

In [1]:
import numpy as np

matriz = np.arange(12).reshape(3, 4)

print("Matriz criada:")
print(matriz)
print("-" * 20)

linha_idx = 1
coluna_idx = 3

# Extrai o elemento usando os índices definidos
elemento = matriz[linha_idx, coluna_idx]

print(f"The matrix element at index ({linha_idx},{coluna_idx}) is {elemento}.")

Matriz criada:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
The matrix element at index (1,3) is 7.
