<a href="https://colab.research.google.com/github/arthur-siqueira/metodos-numericos/blob/main/matrix_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercise 5-1**

In [1]:
import numpy as np

matriz = np.arange(12).reshape(3, 4)

print("Matriz criada:")
print(matriz)
print("-" * 20)

linha_idx = 1
coluna_idx = 3

# Extrai o elemento usando os índices definidos
elemento = matriz[linha_idx, coluna_idx]

print(f"The matrix element at index ({linha_idx},{coluna_idx}) is {elemento}.")

Matriz criada:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
The matrix element at index (1,3) is 7.


**Exercise 5-2**

In [2]:
# Cria a matriz C original (10x10 com números de 0 a 99)
matrix_C = np.arange(100).reshape(10, 10)

print("Matriz Original C (10x10):")
print(matrix_C)
print("\n" + "-"*30 + "\n")

# 2. Usa fatiamento (slicing) para extrair a submatriz C1
# O slice [:5, :5] pega as linhas do índice 0 até 4 e as colunas do índice 0 até 4.
submatrix_C1 = matrix_C[:5, :5]

print("Submatriz Extraída C1 (5x5):")
print(submatrix_C1)

Matriz Original C (10x10):
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

------------------------------

Submatriz Extraída C1 (5x5):
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]
