<a href="https://colab.research.google.com/github/arthur-siqueira/metodos-numericos/blob/main/sistemas_equacoes_lineares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exemplo 2.1**                                                                             
Classificar sistema linear, com relação a quantidade e existência de soluções

In [ ]:
import numpy as np

A = np.array([[2,3,5],[1,-1,10],[-1,1,-1]])
b = np.array([10,20,5])

In [ ]:
np.linalg.matrix_rank(A)

np.int64(3)

In [ ]:
np.linalg.matrix_rank(np.c_[A, b])

np.int64(3)

In [ ]:
A.shape[1]

3

**Exercício 1.1** - Classifique os sistemas abaixo com relação a quantidade e existência de
soluções.

In [ ]:
# a)

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([1,1,1])

In [ ]:
np.linalg.matrix_rank(A)

np.int64(2)

In [ ]:
np.linalg.matrix_rank(np.c_[A, b])

np.int64(2)

In [ ]:
A.shape[1]

# Sistema Possível indeterminado

3

In [ ]:
# b)
A = np.array([[2,3],[-4,-6]])
b = np.array([10, -10])


In [ ]:
np.linalg.matrix_rank(A)

np.int64(1)

In [ ]:
np.linalg.matrix_rank(np.c_[A, b])

np.int64(2)

In [ ]:
A.shape[1]

# Sistema Impossível

2

**Exercício 1.2**

In [ ]:
A = np.array([
    [3, 4, -5,  1],
    [0, 1,  1, -2],
    [0, 0,  4, -5],
    [0, 0,  0,  2]
], dtype=float)
b = np.array([-10, -1, 3, 2], dtype=float)
A, b

(array([[ 3.,  4., -5.,  1.],
        [ 0.,  1.,  1., -2.],
        [ 0.,  0.,  4., -5.],
        [ 0.,  0.,  0.,  2.]]),
 array([-10.,  -1.,   3.,   2.]))

In [ ]:
def sist_lin_tri_sup(A: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Resolve Ax=b para A triangular superior usando substituição retroativa."""
    A = A.astype(float)
    b = b.astype(float)
    n = A.shape[1]
    x = np.zeros(n)
    x[-1] = b[-1] / A[-1, -1]
    for i in range(n-2, -1, -1):
        soma = 0.0
        for j in range(i+1, n):
            soma += A[i, j] * x[j]
        x[i] = (b[i] - soma) / A[i, i]
    return x

x = sist_lin_tri_sup(A, b)
x

array([ 1., -1.,  2.,  1.])

In [ ]:
# Passos explicitos

steps = []
n = A.shape[1]
x_step = np.zeros(n)
x_step[-1] = b[-1] / A[-1, -1]
steps.append((n, f"x_{n} = b_{n}/a_{n} = {b[-1]}/{A[-1,-1]} = {x_step[-1]:.1f}"))
for i in range(n-2, -1, -1):
    s = sum(A[i, j] * x_step[j] for j in range(i+1, n))
    x_step[i] = (b[i] - s) / A[i, i]
    steps.append((i+1, f"x_{i+1} = (b_{i+1} - "+
                 " + ".join([f"a_{i+1}{j+1} x_{j+1}" for j in range(i+1, n)])+
                 f")/a_{i+1}{i+1} = ({b[i]} - {s})/{A[i,i]} = {x_step[i]:.1f}"))

for idx, txt in steps:
    print(txt)

x_step

x_4 = b_4/a_4 = 2.0/2.0 = 1.0
x_3 = (b_3 - a_34 x_4)/a_33 = (3.0 - -5.0)/4.0 = 2.0
x_2 = (b_2 - a_23 x_3 + a_24 x_4)/a_22 = (-1.0 - 0.0)/1.0 = -1.0
x_1 = (b_1 - a_12 x_2 + a_13 x_3 + a_14 x_4)/a_11 = (-10.0 - -13.0)/3.0 = 1.0


array([ 1., -1.,  2.,  1.])

In [ ]:
# Verificação (A,x = b)
Ax = A.dot(x)
print('A·x =', Ax)
print('b   =', b)
assert np.allclose(Ax, b), 'Solução não confere com b.'
print('\nConferido: Ax = b.')

A·x = [-10.  -1.   3.   2.]
b   = [-10.  -1.   3.   2.]

Conferido: Ax = b.


**Exercício 1.3**

In [ ]:
A = np.array([
    [3, 0, 0, 0],
    [2, 1, 0, 0],
    [1, 0, 1, 0],
    [1, 1, 1, 1]
], dtype=float)

b = np.array([4, 2, 4, 2], dtype=float)
A, b

(array([[3., 0., 0., 0.],
        [2., 1., 0., 0.],
        [1., 0., 1., 0.],
        [1., 1., 1., 1.]]),
 array([4., 2., 4., 2.]))

In [ ]:
def sist_lin_tri_inf(A: np.ndarray, b: np.ndarray) -> np.ndarray:
  """Resolve Ax=b para A triangular inferior usando substituição progressiva."""
  A = A.astype(float)
  b = b.astype(float)
  n = A.shape[1]
  x = np.zeros(n)

  x[0] = b[0] / A[0, 0]

  for i in range(1, n):
    soma = 0.0
    for j in range(0, i):
      soma += A[i, j] * x[j]
    x[i] = (b[i] - soma) / A[i, i]
  return x

x = sist_lin_tri_inf(A, b)
x

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [ ]:
# Passos explícitos

steps = []
n = A.shape[1]
x_step = np.zeros(n)
x_step[0] = b[0] / A[0, 0]
steps.append((1, f"x_1 = b_1/a_11 = {b[0]}/{A[0, 0]} = {x_step[0]:.10g}"))
for i in range(1, n):
  s = sum(A[i, j] * x_step[j] for j in range(0, i))
  x_step[i] = (b[i] - s) / A[i, i]
  left = " + ".join([f"a_{i+1}{j+1} x_{j+1}" for j in range(0, i)]) or "0"
  steps.append((i+1, f"x_{i+1} = (b_{i+1} - {left})/a_{i+1}{i+1} = ({b[i]} - {s})/{A[i,i]} = {x_step[i]:.10g}"))

for idx, txt in steps:
    print(txt)

x_step

x_1 = b_1/a_11 = 4.0/3.0 = 1.333333333
x_2 = (b_2 - a_21 x_1)/a_22 = (2.0 - 2.6666666666666665)/1.0 = -0.6666666667
x_3 = (b_3 - a_31 x_1 + a_32 x_2)/a_33 = (4.0 - 1.3333333333333333)/1.0 = 2.666666667
x_4 = (b_4 - a_41 x_1 + a_42 x_2 + a_43 x_3)/a_44 = (2.0 - 3.333333333333334)/1.0 = -1.333333333


array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [ ]:
# Verificação (A,x = b)

Ax = A.dot(x)
print('A·x =', Ax)
print('b   =', b)
assert np.allclose(Ax, b), 'Solução não confere com b.'
print('\nConferido: Ax = b.')

A·x = [4. 2. 4. 2.]
b   = [4. 2. 4. 2.]

Conferido: Ax = b.


**Exercício 1.4**

In [ ]:
from typing import Literal

def _is_diagonal(A: np.ndarray, atol: float=1e-12) -> bool:
  return np.allclose(A - np.diag(np.diag(A)), 0.0, atol=atol)

def _is_upper(A: np.ndarray, atol: float=1e-12) -> bool:
    # zeros na parte inferior estrita
    return np.allclose(np.tril(A, k=-1), 0.0, atol=atol)

def _is_lower(A: np.ndarray, atol: float=1e-12) -> bool:
    # zeros na parte superior estrita
    return np.allclose(np.triu(A, k=1), 0.0, atol=atol)

def _solve_upper(A: np.ndarray, b: np.ndarray) -> np.ndarray:
    n = A.shape[0]
    x = np.zeros(n, dtype=float)
    if np.any(np.isclose(np.diag(A), 0.0)):
        raise np.linalg.LinAlgError('Matriz triangular superior singular (elemento diagonal zero).')
    x[-1] = b[-1] / A[-1, -1]
    for i in range(n-2, -1, -1):
        s = float(np.dot(A[i, i+1:], x[i+1:]))
        x[i] = (b[i] - s) / A[i, i]
    return x

def _solve_lower(A: np.ndarray, b: np.ndarray) -> np.ndarray:
    n = A.shape[0]
    x = np.zeros(n, dtype=float)
    if np.any(np.isclose(np.diag(A), 0.0)):
        raise np.linalg.LinAlgError('Matriz triangular inferior singular (elemento diagonal zero).')
    x[0] = b[0] / A[0, 0]
    for i in range(1, n):
        s = float(np.dot(A[i, :i], x[:i]))
        x[i] = (b[i] - s) / A[i, i]
    return x

def solve_trivial(A: np.ndarray, b: np.ndarray, *, atol: float=1e-12) -> tuple[np.ndarray, Literal['diagonal','upper','lower']]:
    """Resolve Ax=b quando A é diagonal, triangular superior ou triangular inferior.
    Retorna (x, tipo), onde tipo∈{'diagonal','upper','lower'}.
    """
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n, m = A.shape
    if n != m:
        raise ValueError('A deve ser quadrada.')
    if b.shape not in [(n,), (n,1)]:
        raise ValueError('b deve ter dimensão compatível com A.')
    b = b.reshape(n)

    if _is_diagonal(A, atol):
        d = np.diag(A)
        if np.any(np.isclose(d, 0.0, atol=atol)):
            raise np.linalg.LinAlgError('Matriz diagonal singular (elemento diagonal zero).')
        x = b / d
        return x, 'diagonal'

    if _is_upper(A, atol):
        return _solve_upper(A, b), 'upper'

    if _is_lower(A, atol):
        return _solve_lower(A, b), 'lower'

    raise ValueError('A não é diagonal, triangular superior nem triangular inferior (dentro da tolerância).')

In [ ]:
# Exemplo 3.2 — triangular superior
A_sup = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]], float)
b_sup = np.array([-10,-1,3,2], float)
x_sup, kind_sup = solve_trivial(A_sup, b_sup)
print('tipo:', kind_sup, '| x =', x_sup)
print('checagem sup:', np.allclose(A_sup@x_sup, b_sup))

# Exemplo 3.3 — triangular inferior
A_inf = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]], float)
b_inf = np.array([4,2,4,2], float)
x_inf, kind_inf = solve_trivial(A_inf, b_inf)
print('tipo:', kind_inf, '| x =', x_inf)
print('checagem inf:', np.allclose(A_inf@x_inf, b_inf))

# Caso diagonal
A_diag = np.diag([2, -3, 5])
b_diag = np.array([6, 3, 10], float)
x_diag, kind_diag = solve_trivial(A_diag, b_diag)
print('tipo:', kind_diag, '| x =', x_diag)
print('checagem diag:', np.allclose(A_diag@x_diag, b_diag))

tipo: upper | x = [ 1. -1.  2.  1.]
checagem sup: True
tipo: lower | x = [ 1.33333333 -0.66666667  2.66666667 -1.33333333]
checagem inf: True
tipo: diagonal | x = [ 3. -1.  2.]
checagem diag: True
